### PR TITLE
View materialization

### PR DESCRIPTION
**Pull request by gunnarmorling**
@jpechane Here you go :)

Instructions are very basic still, I'll expand later on (to make the motivation more apparent etc.)

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane Any thoughts?

**Comment by jpechane** [comment]
Why is there `json-expansion-smt/json-expansion-smt-1.0.0.Final.jar`?

**Comment by gunnarmorling** [comment]
It's added for the purposes of the S2I build. Happy to refine, but I wanted to get something done quickly and possible come back to it later on.

**Comment by gunnarmorling** [comment]
@jpechane Any thoughts welcomed for doing this more nicely! I'm going to merge this one, so Emmanuel can do a first run through the instructions.

**Pull request closed without merging**
